apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: nd-1
spec:
  selector:
    yum: why
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 3023