apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: nd-1
spec:
  selector:
    yum: why
  type: NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80
    nodePort:  30023
    protocol: TCP