apiVersion: v1
kind: ReplicationController
metadata:
  name: replication
spec:
  replicas: 4
  selector: 
    app: rc
  template:
    metadata:
      name: replicationpod
      labels:
        app: rc
    spec:
      containers:
        - name: replica-containers
          image:  tomcat
          ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name:  rc.svc
spec:
  selector:
    app:  rc
  type:  NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  8080
     
